### ISSUE TITLE
Allow creation of artist page even if wiki page already exists

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3249] opened 2017-07-29 23:44 UTC
I've hit some cases of a wiki page existing for an artist, but not the actual artist page.

In order to create the artist page, it appears that I have to remove the artist tag from all of its posts, then rename the wiki page to something, then create the artist page, then rename the wiki page back again, then re-add the artist tag...

**Comment by BrokenEagle** [comment] 2017-07-30 18:43
This is related to issue #2717.  Basically, the above block was put into place to prevent someone from creating an artist that already had an existing wiki, especially if it is for an existing general. character or copyright tag.  A fix for the above could involve only blocking the creation of an artist if the wiki page is not of the artist tag category.

Anyways, the blocks are only put on the artist endpoint.  One short-term solution for the above then is to temporarily rename the wiki page, create the artist page, then rename the wiki page back.  The wiki page will complain about moving all of the posts, but there was a **Force Rename** option I was able to take advantage of.  The **Force Rename** option only shows up after you first try submitting and getting the error message.

1. Temporarily rename wiki page, and get error message
2. Select **Force Rename** and submit again.
3. Create artist page
4. Rename wiki page back (no error message this time)

I tested out and validated the above procedure with the following Testbooru pages:

http://testbooru.donmai.us/artists/7
http://testbooru.donmai.us/wiki_pages/10

**Comment by evazion** [comment] 2017-07-31 19:47
I mentioned this in #2717, but IMO the validation should just be that the artist name doesn't conflict with an existing general/character/copyright tag.

> Anyways, the blocks are only put on the artist endpoint. One short-term solution for the above then is to temporarily rename the wiki page, create the artist page, then rename the wiki page back. 

Another workaround is to use a dummy name when creating the artist entry, then rename it to the real name afterwards. The validation only applies at creation time (really it should be whenever the artist's name changes).

**Comment by evazion** [comment] 2019-07-30 03:45
Duplicate of #3249

**Closed by evazion** 2019-07-30 03:45 UTC
Labels: wontfix
