### ISSUE TITLE
Ugoira thumbnail/webm not displayed

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2576] opened 2016-01-26 18:59 UTC
Two ugoira in the past day didn't have their thumbnail generated:
http://danbooru.donmai.us/posts?tags=id%3A2255188%2C2256694

I don't think the delayed job for generating them is backed up, as it doesn't appear anywhere in [the delayed job list](http://danbooru.donmai.us/delayed_jobs?limit=1000). Also, their webms seem to be fine, even though the webm and thumbnail are generated by the same delayed job.

**Comment by ToksT** [comment] 2016-01-26 19:06
Upon closer inspection, the thumbnails exist on sonohara, but not hijiribe:
http://sonohara.donmai.us/posts?tags=id%3A2255188%2C2256694
http://hijiribe.donmai.us/posts?tags=id%3A2255188%2C2256694

And on sonohara, a different set of ugoira don't have thumbnails:
http://sonohara.donmai.us/posts?utf8=%E2%9C%93&tags=id%3A2252303%2C2250337%2C2250159
http://hijiribe.donmai.us/posts?utf8=%E2%9C%93&tags=id%3A2252303%2C2250337%2C2250159

Something related to distributing the file across the servers?

**Comment by ToksT** [comment] 2016-02-02 16:22
Also it seems webms actually are affected for many of the affected posts (though not 100% of them).

**Comment by r888888888** [comment] 2016-02-04 01:01
I suspect this was caused by ugoira transfers taking awhile, and the file uploader not overwriting on dupes. This was fixed in 48aa4cc3d69ccf0eeb785852d6c938a3b3d4a0ce and 3d9b7f797a87d348b5d6aeb94d948f6124843aae.

**Closed** 2016-02-18 00:34 UTC
Labels: Bug
