### ISSUE TITLE
Search attempt displays error message

### ISSUE THREAD

**Issue by indomitable52** [r888888888/danbooru#3057] opened 2017-05-15 11:48 UTC
undefined method `any?' for nil:NilClass

**Comment by indomitable52** [comment] 2017-05-16 22:22
I don't remember what I searched and didn't think to screenshot the page, but it just had the header, search bar, that message, and footer. I'll screenshot it and file another report if I see this again.

**Comment by evazion** [comment] 2017-07-25 01:44
Closing due to inability to reproduce and lack of further details.

**Closed by evazion** 2017-07-25 01:44 UTC
