### ISSUE TITLE
Separate API Limits by Writes/Reads

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2693] opened 2016-09-29 19:33 UTC
After writing my reversion tool, I realized how easy it would be for a tech savvy person to seriously vandalize the site with one or more member level accounts since the API limit does not differentiate between reads and writes, and member-level accounts have a limit of 3000.  That's 3000 potential writes per hour for each account they attack from.  This shouldn't be, as reads are usually benign whereas writes aren't necessarily.  

It's true that any user's changes can be easily reverted, however, consider how much superfluous data is created and has to be stored for perpetuity.  A persistent user could keep at it over time, growing all of the version tables at a faster rate than they have traditionally grown, which may or may not be an issue...?

**Comment by r888888888** [comment] 2016-09-29 19:45
There's a danger here of changing expectations of users by reducing access. I'm not sure what a suitable number of write limits is.

**Comment by BrokenEagle** [comment] 2016-09-29 20:12
I think only member-level accounts should be limited, since paid/earned accounts have something to lose if they get banned.  I would set the write limit to no more than 300 writes, and maybe even as low as 100 writes.  That's about the same amount of writes a normal user could perform through a web browser.

**Comment by evazion** [comment] 2016-10-18 08:09
From http://danbooru.donmai.us/forum_topics/9127?page=136:

> Hi, JSON api woes, trying to GET /posts.json without session results on a HTML page saying "wrong number of arguments (given 1, expected 0)" instead of JSON with actual data or a response

Looks like 87447a5 introduced a bug; reverting back to ced7a34 works.

**Comment by evazion** [comment] 2016-10-18 08:34
A couple issues:

* API limits are IP-based, not user-based, so you can easily evade write limits by switching IPs. But if they were user-based, then you could just switch accounts instead. So they should be tied to both your username and IP such that you have to change both.

* Rate limits apply only to JSON/XML responses, not HTML. But the problem is that for writes you don't usually need the response, you can just do HTML requests and bypass the write limit.

So to be effective it needs to apply to the web interface too. Of course, the problem then is not impacting legitimate usage. But I think it would be good if write limits did apply for the web interface, that could help limit vandalism.

**Comment by BrokenEagle** [comment] 2016-10-18 16:16
Just throwing this idea out there, but in addition to the above, would it be beneficial to be able to purge version data (*_versions) or instance data (everything else) if needed...?  Is there any reason to keep around data involving vandalism or any other kinds of mistakes (e.g. admin BURs) for perpetuity?

**Comment by r888888888** [comment] 2016-10-18 20:07
Deployed a fix for the anonymous access.

**Comment by BrokenEagle** [comment] 2016-10-19 01:59
Just tested this out as a member-level user on Testbooru and it works fine, however when checking the JSON under /users, it says I have a write limit of 3000 instead of only 300.

I think changing [Line 22 of the API Limiter](https://github.com/r888888888/danbooru/blob/master/app/logical/api_limiter.rb#L22) from...
`CurrentUser.user.api_hourly_limit - requests`
...to...
`CurrentUser.user.api_hourly_limit(idempotent) - requests`
...should fix it.

**Comment by RaisingK** [comment] 2016-10-19 19:35
If I'm reading this right, that's 2000 writes/hour for me now?  That's a rather severe cut to be applying to even Platinum+.  Last time I ran [my bad_id scan](http://danbooru.donmai.us/forum_posts/79030), I exceeded 4000 writes in the first hour just adding/removing bad_id (which aren't the only writes it does).

**Comment by r888888888** [comment] 2016-10-19 20:00
I'll raise it to 5000 for platinum+.

**Comment by evazion** [comment] 2016-10-19 20:18
Small bug in [User#remaining_api_hourly_limit](https://github.com/r888888888/danbooru/blob/25028f0c7f21d630d62c73c62bbc990296b7bee6/app/models/user.rb#L630-L640):

```
    def remaining_api_hourly_limit
      ApiLimiter.remaining_hourly_limit(CurrentUser.ip_addr, true)
    end

    def remaining_api_hourly_limit_read
      ApiLimiter.remaining_hourly_limit(CurrentUser.ip_addr, true)
    end

    def remaining_api_hourly_limit_write
      ApiLimiter.remaining_hourly_limit(CurrentUser.ip_addr, false)
    end
```

Should be CurrentUser.id, since the cache key was changed from ip addrs to user ids.

**Comment by evazion** [comment] 2016-10-19 20:29
> Just throwing this idea out there, but in addition to the above, would it be beneficial to be able to purge version data (*_versions) or instance data (everything else) if needed...? Is there any reason to keep around data involving vandalism or any other kinds of mistakes (e.g. admin BURs) for perpetuity?

IMO it's probably not worth bothering. I think the worst recent mistake was the poorly_drawn implications and that was only a few thousand edits IIRC. Compared to ~16.5m total edits in the post versions table, that's nothing.

**Comment by BrokenEagle** [comment] 2016-10-19 20:46
Just copying over an issue first reported on Danbooru...

In the [api_hourly_limit](https://github.com/r888888888/danbooru/blob/master/app/models/user.rb#L614) function in the users model, if the user doesn't have an API key, it defaults the number of writes to 300, which can affect things like tag scripts through the web interface.

See page [136](http://danbooru.donmai.us/forum_topics/9127?page=136) and [137](http://danbooru.donmai.us/forum_topics/9127?page=137) of the Danbooru 2 Issues topic for an example of a user that experienced this.

**Comment by BrokenEagle** [comment] 2016-10-20 02:15
Found a bug with the recent commits...

API read/writes are no longer being counted.

It might be related to [commit 2424f24](https://github.com/r888888888/danbooru/commit/2424f24fcdf749bd1dd80ecf2f5c66f4714b382d), when it was switched from user the IP address to the user key, i.e. (CurrentUser.id || request.remote_ip).

**Comment by r888888888** [comment] 2017-01-06 02:10
I've decided to implement a [token bucket](https://en.wikipedia.org/wiki/Token_bucket) algorithm for rate limiting. This will necessitate creating a new database table. To cut down on bloat only writes will be rate limited. Anonymous users will share a rate limit to simplify implementation but they will have an inflated limit to account for the fact it represents multiple users.

**Comment by evazion** [comment] 2017-01-06 03:12
I was fixing some of these bugs in PR #2821, I'll stop and let you look at it and see what can be merged.

I included the limits in the HTTP headers because that solves an issue where you have to check /users/$id.json to see your limits, but if you're anonymous or if you're throttled you can't do that. This is modeled on github's API.

**Comment by evazion** [comment] 2017-01-06 03:28
The only non-GET endpoints accessible to anon users I know of are `POST /dtext_previews` and `POST /iqdb_queries`. But they don't modify anything, so they don't really need to be POST.

Also I just noticed that tag autocompletion hits the API, one call per character typed unless the tag is cached. Anon users can easily hit their read limit that way. [Throttling/debouncing](https://css-tricks.com/debouncing-throttling-explained-examples/) the ajax calls while the user is typing would help here.

**Comment by r888888888** [comment] 2017-01-06 23:50
The new token bucket algorithm is being sketched out in https://github.com/r888888888/danbooru/tree/token-bucket

From a user's perspective you can effectively make r requests per second, and make b requests in a single burst. This burst pool is slowly regenerated at r tokens per second. I think the end result is that it's a lot more usable, assuming the numbers are tweaked a bit.

Currently only writes are covered but some DDOS-sensitive endpoints could situationally be rate limited also.

**Comment by evazion** [comment] 2017-01-07 01:05
Looks good to me. From the looks of it:

* Limits are write only. They don't apply to anonymous users or GET/HEAD requests.
* They do apply to .html/.js requests now, but actions on favorites, post votes, and /users are exempted.
* `X-Api-Limit` holds your current remaining requests.
* Limits are shared between servers.
* The limits are currently 1 write per second for non-gold, 2 per sec. for gold, 3 per sec. for platinum+. That works out to 3600, 7200, or 10800 writes per hour.

For a point of reference, all three of us (me, BrokenEagle, and RaisingK) were doing 250-300 writes per second in the `bad_pixiv_id` tagging, or 4-5 per second. So the hourly limits are higher but the rate-per-second is slightly lower.

Only issue I see is the effective hourly limit for members being much higher now. It could be lowered, but might have to raise the burst limit a lot to compensate.

**Comment by BrokenEagle** [comment] 2017-01-07 19:22
I agree with evazion here... the hourly limit is 2x for Platinum, 7x for Gold, and 12x for Member.  Does the rate limit have to be integers...? If not, the current regen levels should at least be halfed if not more. 

Also just thinking out loud, but would it be useful to have some kind of Mod/Admin notification system for user accounts going at the max-limit or close to it for a certain time period, i.e. going full blast with writes.  An unknown user going full-out for more than an hour would bear some investigation IMO...

**Closed** 2018-09-19 23:29 UTC
