### ISSUE TITLE
Uploading: appearance depending on if "Include Commentary" is checked

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2459] opened 2015-07-25 22:26 UTC
When "Include Commentary" is _not_ checked, grey-out the artist commentary fields.  When it _is_, display links next to it for `commentary_request` and `commentary` that add their respective tags to the list.

**Comment by evazion** [comment] 2019-07-30 05:41
Second item is a duplicate of #2794.

**Closed by evazion** 2019-07-30 05:41 UTC
Labels: wontfix
