### ISSUE TITLE
"Too Many Requests" errors being reported

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3023] opened 2017-05-04 05:40 UTC
This is being reported on the forums as a recent issue.  Several builders are reporting this, and they also report not doing anything beyond the usual.

http://danbooru.donmai.us/forum_topics/9127?page=180#forum_post_130750

**Comment by evazion** [comment] 2017-05-04 05:58
Seems like a server issue. There haven't been any changes related to API limits lately and I can't reproduce this on my devbooru.

I notice that my profile says my limit is 60 / 60 where normally it says 59 / 60. It never goes down either. But if I tag script a few posts then check the `X-Api-Limit` headers in the dev console, they says my limit is fluctuating around -15 to -20.

**Comment by Type-kun** [comment] 2017-05-04 12:08
Hmm, if I had to guess, time has gone out of sync on rails server(s) and postgresql server. 

Token bucket model says:
```
# estimate the token count to avoid reloading
    self.token_count += user.api_regen_multiplier * (Time.now - last_touched_at)
    self.token_count = user.api_burst_limit if token_count > user.api_burst_limit
```
`last_touched_at` is calculated on the postgresql server using `now()`. If it ends up greater then the value returned by `Time.now`, then user's tokens will be increased by negative value, even though DB value will be stored and reported correctly (assuming token bucket model doesn't call `save` at some point).

As for why it always says `59/60` and now says `60/60` - I observe the same thing, but can't tell what's happening., or why it has been returning `59` earlier, for that matter.

**Comment by BrokenEagle** [comment] 2017-05-04 15:42
I believe a big part of this is that many of the users reporting a problem have an API limit of only 10, even though they are builders and  so should have a limit of 60.  This is because the you only get an increase in your limit based on your user level **and if you have an API_KEY**.  

I thought this was changed a while back since all requests count towards your API limit, not just JSON and XML...?  Is there any reason why that API_KEY conditional shouldn't be removed...?

**Comment by Type-kun** [comment] 2017-05-04 17:55
It's a problem as well, but not the root of this case. I encountered restrictions after 3 tag script edits, as well, despite having 60 burst limit.

**Comment by evazion** [comment] 2017-05-04 18:15
> As for why it always says 59/60 and now says 60/60 - I observe the same thing, but can't tell what's happening., or why it has been returning 59 earlier, for that matter.

I think that's because the token count is only refreshed during POST/PUT requests. If you make a bunch of edits then check your profile, you'll see your API limit stays at a lowered value until you make another API request. You can see this on testbooru (which btw is working).

**Comment by evazion** [comment] 2017-05-04 18:26
> Hmm, if I had to guess, time has gone out of sync on rails server(s) and postgresql server.

Makes sense. My other thought would be some kind of database corruption, since `token_buckets` is stored as an unlogged table. The fact that profiles always say `60 / 60` sounds like it means the token bucket doesn't exist and so it defaults to `api_burst_limit`:

```ruby
# app/models/user.rb
def remaining_api_limit
    token_bucket.try(:token_count) || api_burst_limit
end
```

**Comment by r888888888** [comment] 2017-05-07 01:26
Database server was set to central time for some reason. I had to restart it and probably need to run vacuum analyze again.

**Comment by evazion** [comment] 2017-05-07 03:32
Site is back up but this is still happening. Can the api limits just be disabled for the time being?

**Comment by r888888888** [comment] 2017-05-07 03:57
I believe this is fixed in 1b5d409c0c7d9c07b318784a252350cac710b85a

**Comment by r888888888** [comment] 2017-05-07 03:58
Postgres is somehow thinking it's in UTC time zone which was causing the math to fail. Using the postgres now() function is probably ill advised: the db server doesn't have access to the internet so even the NTP daemon doesn't work.

**Closed** 2017-05-07 05:35 UTC

**Comment by Type-kun** [comment] 2017-05-07 06:47
>Postgres is somehow thinking it's in UTC time zone which was causing the math to fail. Using the postgres now() function is probably ill advised: the db server doesn't have access to the internet so even the NTP daemon doesn't work.

In that case it's probably better to set up an NTP server on main rails server and have postgres and supplementary servers sync with it. We can't know where db time is used internally, so having it wrong is a time bomb.
