### ISSUE TITLE
Apostrophes don't appear correctly when quoting another user's comment

### ISSUE THREAD

**Issue by crs00** [r888888888/danbooru#3942] opened 2018-10-03 00:13 UTC
Noticed in https://danbooru.donmai.us/posts/3274146#comment-1856650 that quoting a comment containing an apostrophe slightly breaks dtext quotes and causes apostrophes to become `&#39;`. I've only noticed this happening for apostrophes in comments being quoted so far.

**Comment by evazion** [comment] 2018-10-03 00:31
Duplicate of #3939.

**Closed by evazion** 2018-10-03 00:31 UTC
