### ISSUE TITLE
Post only "half" in a pool

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#2092] opened 2014-01-15 21:15 UTC
[Post #1593458](https://danbooru.donmai.us/posts/1593458) says it's in the "Disgustingly Adorable" pool, but the prev and next links aren't actually linked. The post doesn't show up in the pool listing and it's not in the pool's history either.

**Comment by evazion** [comment] 2016-09-03 08:12
Found two more:

https://danbooru.donmai.us/posts/1407661.xml
https://danbooru.donmai.us/posts/1593451.xml

They have `pool:903` in their `pool_string` but aren't in the pool's `post_ids`:

https://danbooru.donmai.us/pools/903.xml

The result is that they appear in a [ordpool:903](https://danbooru.donmai.us/posts?tags=ordpool%3A903) search but not in [/pools/903](https://danbooru.donmai.us/pools/903).

**Comment by evazion** [comment] 2018-02-12 21:27
I believe this is the same bug as #3091. The root cause was fixed by #3095, but as mentioned in #3091, existing bugged pools still need to be fixed.

**Closed** 2018-09-18 23:58 UTC
Labels: Bug
