### ISSUE TITLE
artist names beginning with underscore (U+005F)

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#2613] opened 2016-06-22 23:29 UTC
Creating an artist entry with underscores "_" (U+005F) shows without the underscore in browsing view.

**Comment by Type-kun** [comment] 2016-09-08 19:51
@Kikimaru what is browsing view, exactly?

Underscores in artist entries are converted to spaces in certain places, namely artist page (`/artists/<number>`) titles. Leading underscore is converted to leading space and subsequently consumed by browser because there's already a space after `Artist: `. Listing (`/artists`) shows all underscores properly, including leading underscores.

User pages suffered from the same, but username underscore replacement is more intelligent - it's a regexp that replaces underscores in the middle of the name, but leaves start/end intact. Maybe the same should be applied to artists?

**Comment by evazion** [comment] 2018-08-28 20:14
Dupe of #1736. Artist names with leading/trailing underscores are no longer allowed (#2882). All such artist entries have been renamed.

**Closed by evazion** 2018-08-28 20:14 UTC
