### ISSUE TITLE
Artist pages show no urls on editing

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3632] opened 2018-04-13 00:21 UTC
Seems all the other info is displayed correctly, but opening any artist page for editing for me shows an empty url box. Examples: 
https://danbooru.donmai.us/artists/101264/edit
https://danbooru.donmai.us/artists/101037/edit

And it seems submitting new urls will basically overwrite the old entry, removing any that are not entered again...

**Comment by BrokenEagle** [comment] 2018-04-13 04:37
Not sure if this is related to the above, but using the delete action on an artist strips all of the URLs out of that entry as well.  Probably unintended behavior, as it behooves us to keep that information in the case of accidental deletions.

Right now, the current procedure for deleting an artist requires copying all of the URLs, deleting the artist, editing that artist and pasting all of those URLs in.

**Comment by r888888888** [comment] 2018-04-13 19:26
I would rather keep `url_string` an attribute since it meshes with the new change tracking functionality better. It is a bit harder to figure out if it's working correctly, admittedly.

Fixed in 06559c4a

**Closed by r888888888** 2018-04-13 19:26 UTC
