### ISSUE TITLE
Wiki Post Previews and  Blacklist Box

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3183] opened 2017-06-24 03:20 UTC
There used to be recent posts visible from the wiki and artist pages but it was commented out in issue #2234.   Does the issue still exist, and if it does, then should the vestigial code be removed, or if it doesn't, then should post previews be reinstated...?

Example of vestigial code:

https://github.com/r888888888/danbooru/blob/master/app/views/wiki_pages/_sidebar.html.erb#L4
https://github.com/r888888888/danbooru/blob/master/app/views/wiki_pages/show.html.erb#L37
https://github.com/r888888888/danbooru/blob/master/app/views/wiki_pages/new.html.erb#L18
https://github.com/r888888888/danbooru/blob/master/app/views/wiki_pages/show_or_new.html.erb#L19

The artist post preview code was removed in [ec6b240](https://github.com/r888888888/danbooru/commit/ec6b2406b6b0629785869ee9f22c239e17cba2f3).

**Edit:**
Additionally as a side issue, the Blacklist javascript code doesn't need to run if $("#blacklist-box").length == 0.  It'll save extra processing cycles if that code doesn't run unnecessarily.

**Comment by evazion** [comment] 2017-06-25 16:37
The previous issue with timeouts was caused by Postgres choosing a suboptimal query plan. Instead of using the tag index, it would sometimes choose to scan the posts table by post id to find the 10 most recent posts, which degrades to a full table scan if the tag has fewer than 10 posts.

I think Postgres is better tuned these days, so I think the previews could be safely reenabled.

**Comment by r888888888** [comment] 2017-06-29 20:18
Reverted in c4503e9971e5fdd84c852c5570b2cc69c548ed94

**Comment by evazion** [comment] 2017-07-03 20:13
> Additionally as a side issue, the Blacklist javascript code doesn't need to run if $("#blacklist-box").length == 0. It'll save extra processing cycles if that code doesn't run unnecessarily.

Fixed in cda3549. Note that this means blacklists won't run on pages that don't have blacklist controls, but there shouldn't be any pages like that left after #3121.

**Comment by BrokenEagle** [comment] 2017-07-04 07:16
> Note that this means posts won't be hidden on pages that don't have blacklist controls, but there shouldn't be any pages like that left after #3121 (except for the modqueue, where posts are deliberately not hidden).

Actually, I noticed another page without blacklist-controls.

http://danbooru.donmai.us/reports/upload_tags?user_id=23799

**Comment by evazion** [comment] 2017-07-06 00:42
Fixed in 68bf355542fb8e794d30d43212ec5333d6bd65d9

**Comment by BrokenEagle** [comment] 2017-07-12 00:45
Found a few more pages without blacklist controls...

http://danbooru.donmai.us/pools/###/order
http://danbooru.donmai.us/favorite_groups/###/order

The above is pretty crippling with the anti-flicker CSS I developed in the [CSS Thread](http://danbooru.donmai.us/forum_posts/132142) as no posts get shown since no post preview starts with the class "blacklisted".  In the interim, I'll just have to add some CSS rules with higher specificity for those or any other pages I find.

**Comment by evazion** [comment] 2017-07-12 02:27
Fixed in ed7b80c0168e4639ad3b6d2fe170ed62bcbb6f87.

I'm going to close this issue since the original problem with wiki previews has been fixed. Reopen #3121 if more pages are found.

**Closed by evazion** 2017-07-12 02:27 UTC
