### ISSUE TITLE
No Post Versions since 4/10

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2969] opened 2017-04-11 18:52 UTC
Currently, the [latest edit](http://danbooru.donmai.us/post_versions) was 2017-04-09 23:51-04:00...

**Comment by r888888888** [comment] 2017-04-11 19:45
The server was restarted and because of ownership on /var/run/archives the service didn't start automatically.

**Comment by kittey** [comment] 2017-04-11 22:12
Well, post versions are back, but they’re not being merged or not being merged correctly.

On [post #2687202](https://danbooru.donmai.us/post_versions?search[post_id]=2687202) my three edits didn’t get merged. I also appear to have removed the source three times, twice in one edit even.

On [post #2688564](https://danbooru.donmai.us/post_versions?search[post_id]=2688564) I supposedly removed a bunch of tags that the post wasn’t even tagged with until 20 minutes later.

**Comment by evazion** [comment] 2017-04-11 23:53
It looks like archives merges based on the current time, when it should be on the time difference between the two post versions.

The incorrect tag removals are because `/post_versions` calculates the diff from the previous version to find removed tags, but I think it chooses the wrong thing as the previous version. It orders by the `version` field to find the previous version, but if you check the json responses you can see the version fields are messed up: some versions are duplicated, some versions are skipped, some versions are out of order w.r.t. update time.

This makes me wonder: is sqs guaranteed to deliver messages in the same order they're sent? If not, archives may not use the correct previous version when calculating diffs. And is more than one queue worker running? If so, it may there may be race conditions in having two workers both adding versions to the same post at the same time.

**Comment by r888888888** [comment] 2017-04-12 18:39
I've updated oumae.donmai.us to automatically restart the services if the machine gets restarted during maintenance so I don't think the merge issues will be happen going forward.

The problem is the 1.hour.ago threshold to check whether a version should be merged. If the service goes down, then all versions that get processed will fail that check and therefore nothing will be merged. Either this timestamp needs to be persisted somewhere (kind of tricky), or maybe an alternative is to get rid of the time check altogether. I think testing the updater should be sufficient.

SQS messages are not guaranteed to be ordered, but there's only one worker and ordering only matters within the scope of a single post so unless someone spams updates the likelihood they get processed out of sequence is low. And in that case the updates should get merged anyway.

I've run a fix on the versions created since April 9 (when the downtime occurred) so the listings should be fixed.

**Comment by Type-kun** [comment] 2017-04-14 18:37
>The problem is the 1.hour.ago threshold to check whether a version should be merged. If the service goes down, then all versions that get processed will fail that check and therefore nothing will be merged. Either this timestamp needs to be persisted somewhere (kind of tricky), or maybe an alternative is to get rid of the time check altogether. I think testing the updater should be sufficient.

Can't we compare `previous.updated_at` to `subject.updated_at` instead of current date? If queue can get stalled, that seems like a logical thing to do.

**Comment by r888888888** [comment] 2017-04-14 19:09
That makes sense. I've pushed a fix on archives.

**Closed by r888888888** 2017-04-14 19:09 UTC
Labels: Bug
