### ISSUE TITLE
Post undeletion does not always create a mod action

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1797] opened 2013-06-22 23:10 UTC
A couple times I've noticed undeleted posts not creating a "(Janitor) undeleted post #(id)" mod action. It does work sometimes, however.

Example posts: http://danbooru.donmai.us/posts/1443869, http://danbooru.donmai.us/posts/726297

**Comment by evazion** [comment] 2017-04-29 04:31
Duplicate of #2771, fixed in #2774.

**Comment by evazion** [comment] 2017-06-12 23:53
Closing as fixed as per previous comment.

**Closed by evazion** 2017-06-12 23:53 UTC
Labels: Bug
