### ISSUE TITLE
Unable to Create New Topics With 255 Characters or Less

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2913] opened 2017-03-03 15:37 UTC
From the [Danbooru forums](http://danbooru.donmai.us/forum_topics/9127?page=161#forum_post_127788):

> Mikaeri said:
> 
> When I try to make a new forum topic, I get this error message saying it requires my title to be 255 characters or more. Isn't this a mistake? It should be less, shouldn't it?

Confirmed the above behavior on Testbooru. http://testbooru.donmai.us/forum_topics

Additionally, the names of topics can no longer be updated without making them 255 characters long, although at least the body of the first post can be updated without the error.

**Comment by evazion** [comment] 2017-03-03 20:59
I can't reproduce this on my own devbooru. However I do observe these things:

* pool names are also affected
* artist names aren't affected but instead throw a `PG::StringDataRightTruncation exception raised ERROR: value too long for type character varying(255)`
* the above fields are defined as `character varying` in `db/structure.sql`.
* I updated simple_form to 3.4.0 recently, which apparently added support for minlength validations (see https://github.com/plataformatec/simple_form/compare/v3.3.1...master, Aug 2016).

Taking this together, I think there are two problems:

* danbooru's actual schema doesn't match the given schema in `db/structure.sql`: some (all?) `character varying` fields are actually defined as `character varying(255)`.
* simple_form 3.4 is picking this up and generating minlength validations based on this. Possibly a simple_form bug? These should be max length limits.

So I think the fix is to either remove these limits or revert simple_form back to 3.3.1.

**Comment by BrokenEagle** [comment] 2017-03-03 22:27
This limitation also only affects the HTML side of things, as I've been able to create artists and update forum topics through the API.

**Comment by r888888888** [comment] 2017-03-03 23:35
Anything marked as string in the migrations typically translates to varchar(255). I can confirm this is true on forum topics title.

**Comment by Type-kun** [comment] 2017-03-05 07:05
Huh, I was able to create a topic on Testbooru without any problems. Is the issue fixed on main server as well?

**Comment by BrokenEagle** [comment] 2017-03-05 14:52
@Type-kun 

I just went back to Testbooru and the issue is still there.  Is Javascript disabled for you on Testbooru on the browser you use, or is something else going on...?

**Comment by Type-kun** [comment] 2017-03-05 15:05
Uh, no, i have everything enabled, yet it works fine - http://testbooru.donmai.us/forum_topics/17. I'm on the presto-based opera though, it probably doesn't give a damn about `minlength` property of the inputs.

**Comment by BrokenEagle** [comment] 2017-03-05 15:20
Ah, well just for reference, it's not necessary to create a new topic to test the above issue.  The issue also exists when attempting to edit the Title of a topic.

The above issue exists for me in the following browser versions:
- Chrome Version 56

The above issue does not exist for me in the following browser versions:
- Internet Explorer 11
- Firefox 47

**Closed** 2017-03-06 23:12 UTC
