### ISSUE TITLE
Difficult to find comments on posts with blacklisted tags

### ISSUE THREAD

**Issue by OOZ662** [r888888888/danbooru#2866] opened 2017-01-27 23:25 UTC
I left a comment on [this post](http://danbooru.donmai.us/posts/2605869) and wanted to check up on what was going on with the post, however I have gigantic_breasts blacklisted. Even with my blacklist "disabled" (by going to a post search containing blacklisted posts and clicking Disable All; the blacklist settings menu doesn't appear on Comments-related pages) the post will not show up in either the comments history on my user profile nor by manually searching for comments created by my username on posts with the gigantic_breasts tag. Luckily the comment's only a day old on a not-particularly-popular tag so I could just do a search for the post itself.

**Comment by evazion** [comment] 2017-06-13 02:18
Problem was that `/comments?group_by=comment` didn't have blacklist controls. Duplicate of #3121; fixed by #3128.

**Closed by evazion** 2017-06-13 02:18 UTC
