### ISSUE TITLE
NoMethodError Exception on IQDB_Queries using POST_ID.

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3010] opened 2017-04-29 16:57 UTC
Using the post_id for /iqdb_queries? generates an exception at least when using my login and api_key, as well as using the _danbooru_session cookie, however using url as a parameter still works as expected.

The following is what gets returned.

> NoMethodError exception raised
> 
> undefined method `to_model' for #<Array:0x007f4e797c7710> Did you mean? to_xml
> app/controllers/iqdb_queries_controller.rb:38:in `create_by_post'
> app/controllers/iqdb_queries_controller.rb:14:in `index'

It's a bit strange though since the "Find similar" function still works...?

**Comment by evazion** [comment] 2017-04-29 19:09
How are you sending the request? I tried it with 

```javascript
// chrome dev console
$.ajax("https://danbooru.donmai.us/iqdb_queries.json?post_id=2699809")
```

and

```bash
curl -u "evazion:$API_KEY" 'http://danbooru.donmai.us/iqdb_queries.json?post_id=2699809' | jq
```

but I'm not able to reproduce this.

**Comment by BrokenEagle** [comment] 2017-04-29 20:46
1st method (pass auth in URL): requests.post('http://danbooru.donmai.us/iqdb_queries?post_id=2702651&login=BrokenEagle98&api_key=EEF2NgytCxEb8vHI8Ke
l2dOKggAWPe-9iPtc5P6JpWn')

2nd method (pass auth in body): 
requests.post('http://danbooru.donmai.us/iqdb_queries?post_id=2707651',json='login':'BrokenEagle98','api_key':'EEF2N
gytCxEb8vHI8Kel2dOKggAWPe-9iPtc5P6JpWn'})

With both of the above methods and nothing else changed, using the url= parameter still works.

Also, the GET method works exactly the same as the POST method in all cases.

**Comment by evazion** [comment] 2017-04-29 21:59
Hmm, I can reproduce it when using POST but GET works for me:

```python
>>> import requests
>>> key = '(redacted)'
>>> r = requests.get('http://danbooru.donmai.us/iqdb_queries.json?post_id=2702651', auth=('evazion', key))
>>> print(r.json())
[{'post': {'is_banned': False, 'tag_string_general': '1girl artist_name bare_legs bare_shoulders blush boots bracelet breastplate brown_eyes brown_hair cape commentary_request dress fang fire hair_ribbon highres jewelry long_hair ponytail ribbon sleeveless sleeveless_dress smile solo twitter_username yellow_ribbon', 'bit_flags': 0, 'has_visible_children': False, 'down_score': -1, 'is_status_locked': False, 'md5': 'c4d35545e9715d331f9af300b811b267', 'uploader_name': 'Apox', 'tag_string': '1girl artist_name bare_legs bare_shoulders blush boots bracelet breastplate brown_eyes brown_hair cape commentary_request dress dyute_(fire_emblem) fang fire fire_emblem fire_emblem_echoes:_mou_hitori_no_eiyuuou hair_ribbon highres jewelry long_hair ponytail ribbon sleeveless sleeveless_dress smile solo twitter_username yellow_ribbon yuyumi_(yuurei)', 'last_noted_at': None, 'tag_string_character': 'dyute_(fire_emblem)', 'tag_count': 31, 'is_note_locked': False, 'uploader_id': 471951, 'score': 2, 'tag_string_artist': 'yuyumi_(yuurei)', 'rating': 's', 'updated_at': '2017-04-25T21:08:04.561-05:00', 'has_active_children': False, 'pixiv_id': 62561006, 'has_children': False, 'id': 2702651, 'file_url': '/data/c4d35545e9715d331f9af300b811b267.png', 'large_file_url': '/data/sample/sample-c4d35545e9715d331f9af300b811b267.jpg', 'preview_file_url': '/data/preview/c4d35545e9715d331f9af300b811b267.jpg', 'tag_count_general': 27, 'tag_count_copyright': 2, 'file_ext': 'png', 'file_size': 1348678, 'tag_count_character': 1, 'last_commented_at': None, 'image_height': 1697, 'image_width': 1200, 'created_at': '2017-04-24T12:35:29.154-05:00', 'is_rating_locked': False, 'fav_string': 'fav:492695 fav:498317 fav:72775 fav:368551', 'up_score': 3, 'is_deleted': False, 'tag_string_copyright': 'fire_emblem fire_emblem_echoes:_mou_hitori_no_eiyuuou', 'children_ids': None, 'parent_id': None, 'is_flagged': False, 'source': 'https://i.pximg.net/img-original/img/2017/04/24/21/33/00/62561006_p0.png', 'is_pending': False, 'tag_count_artist': 1, 'fav_count': 4, 'has_large': True, 'approver_id': 110655, 'last_comment_bumped_at': None, 'pool_string': ''}, 'width': 128, 'height': 128, 'post_id': 2702651}]

>>> r = requests.post('http://danbooru.donmai.us/iqdb_queries.json?post_id=2702651', auth=('evazion', key))
>>> print(r.text)
  {
    "success": false,
    "message": "undefined method `to_model' for #\u003cArray:0x007f4a470df460\u003e\nDid you mean?  to_xml",
    "backtrace": <snipped>
  }
```

**Comment by BrokenEagle** [comment] 2017-04-29 23:26
I tried the authorization method from your example and I still get the same results, although I did try using the .json extension from your example and that does work.  Did that change recently? It didn't before, which is why I've been HTML scraping the results with my code to get the data returned.

Although, I do take back what I said before about GET and PUT returning exactly the same results.  While I do get a HTTP 500 with both, the GET method without the .json extension returns the following instead using any of the above methods.
```
ActionView::MissingTemplate exception raised
Missing template iqdb_queries/index, application/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby]}. Searched in: * "/var/www/danbooru2/releases/20170428003452/app/views"
app/controllers/iqdb_queries_controller.rb:38:in `create_by_post'
app/controllers/iqdb_queries_controller.rb:14:in `index'
```
However, I still don't know why it works with URL and not with POST_ID when using the HTML format (i.e. without the .json extension).

**Comment by evazion** [comment] 2017-04-30 23:02
> However, I still don't know why it works with URL and not with POST_ID when using the HTML format (i.e. without the .json extension).

It's just because /iqdb_queries had been for internal use only, so it only supported whatever the site's javascript needed it to support. The Similar button next to the source box and the Find Similar link in the sidebar each work a little bit differently:

* the Similar button calls `POST /iqdb_queries?url=...` and wants back HTML.
* the Find Similar link calls `POST /iqdb_queries?post_id=...` with the `Accept: text/javascript` header to get back javascript. `/iqdb_queries.js?post_id=...` should also work.

So `/iqdb_queries?post_id=...` doesn't return HTML because the site's javascript only ever wants a .js response back from it, not HTML.

> I tried the authorization method from your example and I still get the same results, although I did try using the .json extension from your example and that does work. Did that change recently? It didn't before, which is why I've been HTML scraping the results with my code to get the data returned.

I added .json at the same time I added GET support. Sorry, should have made that more clear. Are you able to migrate to `GET /iqdb_queries.json`? I think that's the better fix than fixing post_id to return HTML.

**Comment by BrokenEagle** [comment] 2017-05-01 00:49
Yeah, I migrated my code over, for both URL and POST_ID, and I also changed them so that they both use GET instead of POST. It's working good now.

BTW, this issue came about mostly because of [topic #14004](http://danbooru.donmai.us/forum_topics/14004).  Now that I've got IQDB working, I can post my findings.

**Comment by evazion** [comment] 2017-06-13 02:21
I'm going to close this as this seems to have been solved by switching to `GET /iqdb_queries.json`.

**Closed by evazion** 2017-06-13 02:21 UTC
Labels: Bug
