### ISSUE TITLE
Note sizing bug for negative margins.

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#1692] opened 2013-05-29 17:49 UTC
While trying to inspect #1691 I found something interesting. If you make a note containing a div with negative margins, sizing code will enter the infinite loop.
E.g. make a note with ```<div style="margin: -5px;">Test</div>```, click preview or save, mouse over the note, enjoy the hung-up browser.
Please refrain from banning div tag in notes, though, it seems that it will get useful soon.

**Comment by Type-kun** [comment] 2015-05-05 18:57
Is CSS sanitizer we use intelligent enough to restrict margins to -4px+?

**Comment by ToksT** [comment] 2015-05-08 02:54
> Is CSS sanitizer we use intelligent enough to restrict margins to -4px+?

There's no option for filtering on value, it seems.

It seems the cause of this bug is the `bound_position` function in notes.js. It gets into an infinite loop increasing the size of the note. I'm not sure how to fix this because I don't know what this function is supposed to do, it doesn't seem to make a difference to the size of notes whether I disable or enable it.

**Comment by ToksT** [comment] 2015-05-13 22:38
I commented out the loops causing the bug so it should be fixed. Dunno if doing this will break something else but I haven't found anything so far.

**Comment by ToksT** [comment] 2015-06-20 17:18
I still don't have a clue what that code was supposed to be doing, but commenting it out doesn't seem to have broken notes so fixed.

**Closed by ToksT** 2015-06-20 17:18 UTC
Labels: Bug
