### ISSUE TITLE
Disable submit button on upload page until rating is specified

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2456] opened 2015-07-25 12:05 UTC
If I forget the rating before clicking Submit, the upload page reloads... The information is still there, but it's no longer in 'bookmarklet' mode, with the image preview etc...  Could you disable Submit somehow instead, and maybe bring attention to the need for a rating in some other way?

**Comment by ToksT** [comment] 2015-07-25 14:08
This is how I did it originally. The problem is that some users find it much more convenient to use the rating: metatag to specify rating rather than the radio buttons, so requiring the radio buttons be used (by setting required=true in the html) breaks this.

**Comment by r888888888** [comment] 2015-07-25 16:31
I think it's also confusing to disable the button without explaining why.

A better solution would be to retain the url when an error happens. That should be simple enough.

**Comment by r888888888** [comment] 2015-08-05 00:43
wontfix

**Closed by r888888888** 2015-08-05 00:43 UTC
