### ISSUE TITLE
Hovering over notes while zoomed out in chrome sometimes freezes

### ISSUE THREAD

**Issue by Lightforger** [r888888888/danbooru#2375] opened 2015-05-05 19:07 UTC
Zoom out to max, hover over:
http://danbooru.donmai.us/posts/1392020 top notes
http://danbooru.donmai.us/posts/1318949 one of the bottom notes

And the tab dies. Chrome has pretty good anti-crash and only hangs that single tab.
Doesn't seem to happen in other browsers.

**Comment by ToksT** [comment] 2015-06-20 17:15
Duplicate of #1692

**Closed by ToksT** 2015-06-20 17:15 UTC
Labels: Bug
