### ISSUE TITLE
Can't save artist:group entry: "Error: Name conflicts with a wiki page"

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#4114] opened 2019-07-30 21:02 UTC
Attempting to create new entry for "hecatoncheir" (through artist entry: "nemo_brand").
Unable to save with message: "Error: Name conflicts with a wiki page"
Deleting wiki entry doesn't bypass this limitation.

**Comment by BrokenEagle** [comment] 2019-07-31 02:33
This is a duplicate of #4107.

**Closed** 2019-07-31 17:22 UTC
