### ISSUE TITLE
Weekly / Monthly task to recalculate forum post count per topic

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2411] opened 2015-06-17 16:23 UTC
Since we have monthly tasks anyway, why not recalculate all forum topics' post count? It'll fix #2305 and similar issues, and it is future-proof in case something breaks again. Ideally, this should be done for all denormalized data that doesn't get fully recalculated once in a while, but forum topics is a fairly small set that should be quick to update.

P.s. as for why I'm bringing this out - "Translation request" thread is off by one page, yet again.

**Comment by ToksT** [comment] 2015-06-17 17:48
> P.s. as for why I'm bringing this out - "Translation request" thread is off by one page, yet again.

I think that one's just been that way for a long time, rather than it reoccurring. Albert never said he fixed it.

**Comment by r888888888** [comment] 2015-06-18 19:03
I've fixed the post count but I believe there was a bug with non-janitors and deleted posts causing the count to go off.

**Comment by ToksT** [comment] 2015-06-18 19:53
> I believe there was a bug with non-janitors and deleted posts causing the count to go off.

The change you made in d44495ff9eef6606eb2ceb3f227dd4771c708e8a? I believe that allows non-janitors to view deleted posts on the /forum_posts search page. This issue is about the response_count, which affects the last page link that appears on the /forum_topics index.

Also, can you fix the response count for http://danbooru.donmai.us/forum_topics/8282 too? It's also off, albeit only by 1 post instead of like a dozen.

**Comment by r888888888** [comment] 2015-06-18 19:55
Yes but if the deleted posts are filtered out then the response_count isn't accurate since it includes deleted posts.

**Comment by r888888888** [comment] 2015-06-18 23:41
Search fixed in 7754d72a511282a35c3f3e704f02069677178120

**Comment by r888888888** [comment] 2015-06-18 23:42
I've fixed topic 8282.

**Comment by r888888888** [comment] 2015-06-18 23:49
I would rather fix the causes of these miscounts rather than fix the symptoms monthly. If any more crop up you can either paste them here or create a new issue. But if one of the corrected ones veers off again we'll know there's a bug somewhere.

**Closed by r888888888** 2015-06-18 23:49 UTC
Labels: Enhance
